export const PAINT_LIST_REQUEST= 'PAINT_LIST_REQUEST';
export const PAINT_LIST_SUCCESS= 'PAINT_LIST_SUCCESS';
export const PAINT_LIST_FAIL= 'PAINT_LIST_FAIL';

export const PAINT_DETAILS_REQUEST= 'PAINT_LIST_REQUEST';
export const PAINT_DETAILS_SUCCESS= 'PAINT_LIST_SUCCESS';
export const PAINT_DETAILS_FAIL= 'PAINT_LIST_FAIL';

export const PAINT_SAVE_REQUEST= 'PAINT_SAVE_REQUEST'
export const PAINT_SAVE_SUCCESS= 'PAINT_SAVE_SUCCESS';
export const PAINT_SAVE_FAIL= 'PAINT_SAVE_FAIL';


