export const PAINT_LIST_REQUEST= 'PAINT_LIST_REQUEST';
export const PAINT_LIST_SUCCESS= 'PAINT_LIST_SUCCESS';
export const PAINT_LIST_FAIL= 'PAINT_LIST_FAIL';

export const PAINT_DETAILS_REQUEST= 'PAINT_LIST_REQUEST';
export const PAINT_DETAILS_SUCCESS= 'PAINT_LIST_SUCCESS';
export const PAINT_DETAILS_FAIL= 'PAINT_LIST_FAIL';